app/views/home_views.py
from flask import Blueprint, render_template, session, abort
from flask_session import Session

home_views = Blueprint ('home',__name__)

@home_views.route("/hola/")
def cerrar():
    if session.get('user') and session.get('user')['role']==1:
        return render_template('home/menu_adm.html')
    else: 
        abort(403)


@home_views.route("/")
def cat():
    return render_template('home/cierreSesion.html')


@home_views.route("/terminos")
def term():
    return render_template('reports/terminos.html/')

app/views/login_views.py
from flask import Blueprint, render_template, redirect, url_for, flash, session
from models.user import User
from forms.login_forms import LoginForm

login_views = Blueprint('login', __name__)

@login_views.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.nom_usuario.data
        password = form.contrasenia.data
        user = User.get_by_password(username, password)
        if not user:
            flash('Verifica tus Datos')
        else:
            session['user'] = {'username': user.nom_usuario, 'role': user.rol}  # Almacenamos el ID del usuario en la sesión
            if user.rol == 1:
                # Redireccionar a la vista de administrador
                return redirect(url_for('home.cerrar'))
            elif user.rol == 2:
                # Redireccionar a la vista de empleado
                return redirect(url_for('ventas.sale'))
            else:
                flash('No tienes un rol válido', 'error')
    return render_template('login/login.html', form=form)

@login_views.route('/logout/')
def logout():
    print('Cerrando session')
    session.clear()
    print(session)  # Remueve el ID del usuario de la sesión
    flash('Has cerrado sesión', 'success')
    return redirect(url_for('home.cat'))  # Redirige al formulario de inicio de sesión

app/templates/home/cierreSesion.html
{% block title %}

{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/style2.css') }}">
<div class="banner">
        <h1>Papelería Sandy</h1>
        <a href="{{ url_for('login.login')}}" class="login-link">Iniciar sesión</a>
    </div>

    <div class="spacer"></div> 

    <div class="container-items">
        <div id="category-menu">
          
        </div>
        <div class="item-group">
            <div class="item">
                <figure>
                    <img src="{{ url_for('static', filename='images/Libreta.png') }}" alt="Product">
                </figure>
                <div class="info-product">
                    <h2>Libreta Scribe</h2>
                    <p class="price">Precio $23</p>
                    <p class="description">Libreta Scribe cuadro grande, 100 hojas</p>
                    <p class="calification-icon">
                        <i class="fa fa-heart cora"> </i>
                    </p>
                </div>
            </div>
                <div class="item">
                    <figure>
                        <img src="{{ url_for('static', filename='images/Plastilina.png') }}" alt="Product">
                    </figure>
                    <div class="info-product">
                        <h2>Plastilina</h2>
                        <p class="price">Precio: $11</p>
                        <p class="description">Barra de plastilina color rojo</p>
                        <p class="calification-icon">
                           <i class="fa fa-heart cora red"></i>
                        </p>
                    </div>
                </div>
                <div class="item">
                    <figure>
                        <img src="{{ url_for('static', filename='images/Pritt.png') }}" alt="Product">
                    </figure>
                    <div class="info-product">
                        <h2>Resistol </h2>
                        <p class="price">Precio: $16</p>
                        <p class="description">Resistol en barra chico</p>
                        <p class="calification-icon">
                           <i class="fa fa-heart cora"></i>
                        </p>
                    </div>
                </div>
            </div>
            <div class="item-group">
                <div class="item">
                    <figure>
                        <img src="{{ url_for('static', filename='images/ColoresVividel.png') }}" alt="Product">
                    </figure>
                    <div class="info-product">
                        <h2>Lápices de colores</h2>
                        <p class="price">Precio: $60</p>
                        <p class="description">Colores 24 piezas + 3 incluye color oro, plata y cobre</p>
                        <p class="calification-icon">
                            <i class="fa fa-heart cora red"></i>
                        </p>
                    </div>
                </div>
                <div class="item">
                    <figure>
                        <img src="{{ url_for('static', filename='images/lapicerosBic.png') }}" alt="Product">
                    </figure>
                    <div class="info-product">
                        <h2>Lapicero Bic</h2>
                        <p class="price">Precio: $6</p>
                        <p class="description">Lápicero Bic de color rojo, azul y negro, se venden por separado</p>
                        <p class="calification-icon">
                           <i class="fa fa-heart cora"></i>
                        </p>
                    </div>
                </div>
                <div class="item">
                    <figure>
                        <img src="{{ url_for('static', filename='images/lapizDuo.png') }}" alt="Product">
                    </figure>
                    <div class="info-product">
                        <h2>Lapiz Duo</h2>
                        <p class="price">Precio: $6</p>
                        <p class="description">Lápiz Duo Dixon</p>
                        <p class="calification-icon">
                           <i class="fa fa-heart cora"></i>
                        </p>
                    </div>
                </div>
            </div>
            <div class="item-group">
                <div class="item">
                    <figure>
                        <img src="{{ url_for('static', filename='images/LibretaNorma.png') }}" alt="Product">
                    </figure>
                    <div class="info-product">
                        <h2>Libreta Norma</h2>
                        <p class="price">Precio: $86</p>
                        <p class="description">Libreta Norma rayada, 100 hojas</p>
                        <p class="calification-icon">
                           <i class="fa fa-heart cora"></i>
                        </p>
                    </div>
                </div>
                <div class="item">
                    <figure>
                        <img src="{{ url_for('static', filename='images/LibretaEco.png') }}" alt="Product">
                    </figure>
                    <div class="info-product">
                        <h2>Libreta Ecológica</h2>
                        <p class="price">Precio: $60</p>
                        <p class="description">Libreta Ecológica blanca, 100 hojas</p>
                        <p class="calification-icon">
                           <i class="fa fa-heart cora"></i>
                        </p>
                    </div>
                </div>
                <div class="item">
                    <figure>
                        <img src="{{ url_for('static', filename='images/resistolChico-removebg-preview.png') }}" alt="Product">
                    </figure>
                    <div class="info-product">
                        <h2>Resistol Dixon chico</h2>
                        <p class="price">Precio: $10</p>
                        <p class="description">Resistol en barra chico, 8g</p>
                        <p class="calification-icon">
                           <i class="fa fa-heart cora"></i>
                        </p>
                    </div>
                </div>
            </div>
            <div class="item-group">
                <div class="item">
                    <figure>
                        <img src="{{ url_for('static', filename='images/resistolGrande-removebg-preview.png') }}" alt="Product">
                    </figure>
                    <div class="info-product">
                        <h2>Resistol Dixon grande</h2>
                        <p class="price">Precio: $25</p>
                        <p class="description">Resistol en barra grande</p>
                        <p class="calification-icon">
                           <i class="fa fa-heart cora"></i>
                        </p>
                    </div>
                </div>
                <div class="item">
                    <figure>
                        <img src="{{ url_for('static', filename='images/resistolBully.png') }}" alt="Product">
                    </figure>
                    <div class="info-product">
                        <h2>Resistol Bully</h2>
                        <p class="price">Precio: $11</p>
                        <p class="description">Resistol líquido 110g</p>
                        <p class="calification-icon">
                           <i class="fa fa-heart cora"></i>
                        </p>
                    </div>
                </div>
                <div class="item">
                    <figure>
                        <img src="{{ url_for('static', filename='images/ColoresMapita.png') }}" alt="Product">
                    </figure>
                    <div class="info-product">
                        <h2>Lápices de colores</h2>
                        <p class="price">Precio: $27</p>
                        <p class="description">Lápices de colores Mapita 12 piezas</p>
                        <p class="calification-icon">
                           <i class="fa fa-heart cora"></i>
                        </p>
                    </div>
                </div>
            </div>
            <div class="item-group">
                <div class="item">
                    <figure>
                        <img src="{{ url_for('static', filename='images/plumonesPelikan.png') }}" alt="Product">
                    </figure>
                    <div class="info-product">
                        <h2>Plumón Pelikan</h2>
                        <p class="price">Precio: $34</p>
                        <p class="description">Paquete de plumones de 12 piezas</p>
                        <p class="calification-icon">
                        <i class="fa fa-heart cora"></i>
                        </p>
                    </div>
                </div>
                <div class="item">
                    <figure>
                        <img src="{{ url_for('static', filename='images/pinturaVinci.png') }}" alt="Product">
                    </figure>
                    <div class="info-product">
                        <h2>Pintura Vinci</h2>
                        <p class="price">Precio: $12</p>
                        <p class="description">Pintura Vinci color negro</p>
                        <p class="calification-icon">
                        <i class="fa fa-heart cora"></i>
                        </p>
                    </div>
                </div>
                <div class="item">
                    <figure>
                        <img src="{{ url_for('static', filename='images/papelCrepre.jpg') }}" alt="Product">
                    </figure>
                    <div class="info-product">
                        <h2>Papel crepé</h2>
                        <p class="price">Precio: $10</p>
                        <p class="description">Un pliego de papel crepé,color verde, rosa, amarillo, azul cielo, rojo, morado, entre otros</p>
                        <p class="calification-icon">
                        <i class="fa fa-heart cora"></i>
                        </p>
                    </div>
                </div>
            </div>
    </div>
    <script src="{{ url_for('static', filename='js/menu_cat.js') }}"></script> 
    {% endblock %}
</body>
</html>

app/templates/home/menu_adm.html
{%extends 'base.html'%}

{% block title %}
categorias
{% endblock %}

{% block content %}
{% include 'insearch.html' %}


<div>
    <nav class="titulo"><h1>
        Menú de adminsitrador</h1>
    </nav>
    <nav id="container">
        <a href="{{ url_for('product.productos') }}" class="options op-">
            <p class="text a ">Productos</p>
            <img src="{{ url_for('static', filename='resource/prod.jpg') }}" alt="imagen"  class="img-men">
            </a>

            <a href="{{ url_for('usuario.user') }}" class="options">
                <p class="text b">Personal</p>
                <img src="{{ url_for('static', filename='resource/Usuarios.jpg') }}" alt="imagen" class="img-men" >
            </a>
        
            <a href="{{ url_for('cat.catp')}}" class="options">
                <p class="text c">Categoria</p>
                <img src="{{ url_for('static', filename='resource/cateogrias.jpg') }}" alt="imagen" class="img-men" >
            </a>
        
            <a href="{{ url_for('report.reports') }}" class="options">
                <p class="text d">Venta y Reportes</p>
                <img src="{{ url_for('static', filename='resource/reportes.jpg') }}" alt="imagen" class="img-men" >
            </a>
        </nav>
        
            <nav id="container1">
                
                <a href="{{ url_for('brand.brands')}}" class="options">
                    <p class=" text e">Marcas</p>
                    <img src="{{ url_for('static', filename='resource/marca.jpg') }}" alt="imagen" class="img-men" >
                </a>
                <a href="{{ url_for('supplier.suppliers')}}" class="options">
                    <p class="text f">Proveedores</p>
                    <img src="{{ url_for('static', filename='resource/proveedor.jpg') }}" alt="imagen" class="img-men" >
                </a>
            </nav>
</div>

</header>
{% endblock %}