app/models/categories.py
from .db import get_connection

mydb = get_connection()

class Category:

    def __init__(self, nombre,  id_categoria=None, unidades_totales=None):
        self.id_categoria = id_categoria
        self.nombre = nombre
        self.unidades_totales = unidades_totales
        

    def save(self):
        # Create a New Object in DB
        if self.id_categoria is None:
            with mydb.cursor() as cursor:
                sql = "INSERT INTO category(nombre) VALUES(%s)"
                val = (self.nombre,)
                cursor.execute(sql, val)
                mydb.commit()
                self.id_categoria = cursor.lastrowid
                return self.id_categoria
        # Update an Object
        else:
            with mydb.cursor() as cursor:
                sql = "UPDATE category SET nombre = %s WHERE id_categoria = %s"
                val = (self.nombre, self.id_categoria)
                cursor.execute(sql, val)
                mydb.commit()
                return self.id_categoria
            
    def delete(self):
        with mydb.cursor() as cursor:
            sql = f"DELETE FROM category WHERE id_categoria = { self.id_categoria }"
            cursor.execute(sql)
            mydb.commit()
            return self.id_categoria
            
    @staticmethod
    def get(id_categoria):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT nombre FROM category WHERE id_categoria = { id_categoria }"
            cursor.execute(sql)
            result = cursor.fetchone()
            print(result)
            nombre = Category(result["nombre"], id_categoria)
            return nombre
        
          
    @staticmethod
    def get_all(limit=10, page=1):
        offset = limit * page - limit 
        categoria = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT nombre,id_categoria, unidades_totales FROM category limit { limit } offset { offset }"
            cursor.execute(sql)
            result = cursor.fetchall()
            for cats in result:
                categoria.append(Category(nombre=cats["nombre"],
                                          unidades_totales=cats["unidades_totales"],
                                           id_categoria=cats["id_categoria"]))
            return categoria
    
    @staticmethod
    def count_all():
        with mydb.cursor() as cursor:
            sql = f"SELECT COUNT(id_categoria) FROM category"
            cursor.execute(sql)
            result = cursor.fetchone()
            return result[0]
        
    def __str__(self):
        return f"{ self.id_categoria } - { self.nombre }"
    

    @staticmethod
    def count():
        with mydb.cursor(dictionary=True) as cursor:
            sql= "select count(id_categoria) as total from category"
            cursor.execute(sql)
            result =cursor.fetchone()
            return result['total']

app/forms/category_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class CreateCategoryForm(FlaskForm):
    nombre = StringField('Categoria', 
                           validators=[DataRequired()])

    submit = SubmitField('Guardar')

class UpdateCategoryForm(FlaskForm):
    nombre = StringField('Categoria', 
                           validators=[DataRequired()])

    submit = SubmitField('Actualizar')

app/views/category_views.py
from flask import Blueprint, render_template, redirect ,url_for,request,flash, session, abort
from models.categories import Category
import math

from forms.category_forms import CreateCategoryForm, UpdateCategoryForm
category_view =Blueprint('cat',__name__)

@category_view.route("/categorias/")
@category_view.route("/categorias/<int:page>/")
def catp(page=1):
    if session.get('user') and session.get('user')['role']==1:
        limit=10

        category=Category.get_all(limit=limit, page=page)
        total_cat = Category.count()
        pages = math.ceil(total_cat / limit)
        
        return render_template("/categories/categories.html",
                                categories=category, page=page, pages=pages)
    else:
        abort(403)

@category_view.route("/categorias/crear", methods=('GET','POST'))
def catn():
    if session.get('user') and session.get('user')['role']==1:
        form = CreateCategoryForm()
        if form.validate_on_submit():
            nombre= form.nombre.data
            cat = Category(nombre)
            cat.save()
            return redirect(url_for('cat.catp'))
        return render_template("/categories/create_cat.html", form=form)
    else:
        abort(403)

@category_view.route("/categorias/<int:id_categoria>/editar", methods=('GET','POST'))
def cate(id_categoria):
    if session.get('user') and session.get('user')['role']==1:
        form= UpdateCategoryForm()
        cate=Category.get(id_categoria)
        if form.validate_on_submit():
            cate.nombre=form.nombre.data
            cate.save()
            return redirect(url_for('cat.catp'))
        form.nombre.data =cate.nombre
        return render_template("/categories/edit_cat.html", form=form)
    else:
        abort(403)

@category_view.route('/categories/<int:id_categoria>/delete/', methods =('POST',))
def delete_cat(id_categoria):
    
    #Obtener Cat desde id
    cat = Category.get(id_categoria)
    cat.delete()
    #Enviar datos a form
    return redirect(url_for('cat.catp'))

app/templates/categories/categories.html
{% extends 'base.html' %}

{% block title %}
    Categories
{% endblock %}

{% block content %}
{% include 'search.html'%}
<nav class="titulo">
    <h1>
        <a href="{{ url_for('home.cerrar') }}" class="bpr bpr-ed"> Regresar</a>
        Categorias</h1></nav>
    <a href="{{ url_for('cat.catn') }}">
        <input type="button" value="Añadir categorias" class="bpr bpr-ac">
    </a>
    <nav class="a-table">

        <table id="sale">
            <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th>Unidades totales</th>    
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for cat in categories %}
                <tr>
                    <td>{{ cat.id_categoria }}</td>
                    <td>{{ cat.nombre }}</td>
                    <td>{{ cat.unidades_totales }}</td>
                    <td class="acciones">
                        <a href="{{ url_for('cat.cate', id_categoria=cat.id_categoria) }}">
                            
                            <img src="{{ url_for('static', filename='resource/actualizar.png') }}" alt="actualizar" class="as">
                        </a> 
                        <form method="Post" action="{{ url_for('cat.delete_cat', id_categoria=cat.id_categoria) }}">
                            <input type="hidden" name="page" value="{{ page }}">
                            <button type="submit" onclick="return confirm('¿seguro de borrar este objeto?')" class="ad">
                                <img src="{{ url_for('static', filename='resource/eliminar.png') }}" alt="borrar" class="ad">
                                
                            </button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% for i in range(pages) %}
<a href="{{ url_for('cat.catp', page=(i + 1)) }}" class="pasar">{{ i + 1 }}</a>
{% endfor %}
</nav>
{% endblock %}

app/templates/categories/create_cat.html
{% extends 'base.html' %}

{% block title %}
    Agregar Categoria
{% endblock %}

{% block content %}
<nav class="titulo"> Añadir categorias </nav>

    <form method="Post" class="pdiv">
        {{ form.csrf_token }}
        <div class="func func-cat">
            {{ form.nombre.label( class="txtlab") }}
            {{ form.nombre(placeholder="Nombre", class="margin") }}
            {% if form.nombre.errors %}
                {% for error in form.nombre.errors %}
                    <p>{{ error }}</p>
                {% endfor %} 
            {% endif %}
        </div>

        <div>
            {{ form.submit(class="bpr bpr-ac") }}
        </div>
    </form>
</form>
<a href="{{ url_for('cat.catp') }}" class="btn btn-warning"> Regresar</a>
{% endblock content %}

app/templates/categories/edit_cat.html
{%extends 'base.html'%}


{% block title %}
productos
{% endblock %}

{% block content %}
{% include 'insearch.html' %}
<nav class="titulo"><h1>
    <a href="{{ url_for('cat.catp') }}" class="bpr bpr-ed"> Regresar</a>
    Editar categorias 
</h1>
</nav>


        <form method="Post" class="pdiv">
            {{ form.csrf_token }}
            <div class="func func-cat">
                {{ form.nombre.label( class="txtlab") }}
                {{ form.nombre(placeholder="Nombre", class="margin") }}
                {% if form.nombre.errors %}
                    {% for error in form.nombre.errors %}
                        <p>{{ error }}</p>
                    {% endfor %} 
                {% endif %}
            </div>
    
            <div>
                {{ form.submit(class="bpr bpr-ac") }}
            </div>
        </form>
{% endblock content %}