app/views/login_views.py
from flask import Blueprint, render_template, redirect, url_for, flash, session
from models.user import User
from forms.login_forms import LoginForm

login_views = Blueprint('login', __name__)

@login_views.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.nom_usuario.data
        password = form.contrasenia.data
        user = User.get_by_password(username, password)
        if not user:
            flash('Verifica tus Datos')
        else:
            session['user'] = {'username': user.nom_usuario, 'role': user.rol}  # Almacenamos el ID del usuario en la sesión
            if user.rol == 1:
                # Redireccionar a la vista de administrador
                return redirect(url_for('home.cerrar'))
            elif user.rol == 2:
                # Redireccionar a la vista de empleado
                return redirect(url_for('ventas.sale'))
            else:
                flash('No tienes un rol válido', 'error')
    return render_template('login/login.html', form=form)

@login_views.route('/logout/')
def logout():
    print('Cerrando session')
    session.clear()
    print(session)  # Remueve el ID del usuario de la sesión
    flash('Has cerrado sesión', 'success')
    return redirect(url_for('home.cat'))  # Redirige al formulario de inicio de sesión

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<!--<style>
    .fond
{
 background-image:url("{{ url_for('static', filename='images/fondo.jpg')}}" );
 
}
</style> -->
<title>{% block title %}{% endblock %}</title>
  
</head>
    <body>
        <header>
            <div class="fond">
            {% block content %}
            {% endblock %}
        
</div>
</header>
<footer class="footer">
    <p> Copyright @the Software house</p>

</footer>
</body>
</html>

app/templates/insearch.html
<nav class="grid">
    <img src="{{ url_for('static', filename='resource/logo.png') }}" alt="logo" class="i item">
<a href="{{url_for('login.logout')}}" class="item ins"><p>Cerrar Sesion
</p>
</a>
<nav class="buscadores sps">
Sistema de Punto de Venta

</nav>
</nav>

</nav>

app/templates/search.html
<nav class="grid">
    <img src="{{ url_for('static', filename='resource/logo.png') }}" alt="logo" class="i item">
    <a href="{{url_for('login.logout')}}" class="item ins"><p>Cerrar Sesion</p>
</a>

    <nav class="buscadores" >
        <a href="{{ url_for('product.productos') }}" class="co"> Productos</a>
        <a href="{{ url_for('usuario.user') }}"class="co">Personal</a>   
        <a href="{{ url_for('cat.catp')}}" class="co">Categorias</a>   
        <a href="{{ url_for('report.reports') }}" class="co">Reportes</a>   
        <a href="{{ url_for('brand.brands')}}" class="co">Marcas</a>   
        <a href="{{ url_for('supplier.suppliers')}}" class="co">Proveedores</a>   
    </nav>
    </nav>
</nav>